#!/bin/sh
set -e

# Add a system user for uptime-logger if it doesn't exist.
if ! getent passwd uptime-logger >/dev/null; then
    adduser --system --group --no-create-home --home /var/lib/uptime-logger --shell /bin/false uptime-logger
fi

echo "Creating data directory..."
mkdir -p /var/lib/uptime-logger
chown uptime-logger:uptime-logger /var/lib/uptime-logger
chmod 0750 /var/lib/uptime-logger

echo "Reloading systemd daemon..."
systemctl daemon-reload

echo "Enabling systemd services..."
systemctl enable uptime-logger.service
systemctl enable uptime-logger-shutdown.service

exit 0
