#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    # Remove the directory, but only if it is empty.
    rmdir --ignore-fail-on-non-empty /var/lib/uptime-logger || true
fi

# Just in case services are still referenced
systemctl daemon-reload || true

exit 0