name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev libcurl4-openssl-dev

      - name: Build .deb package
        run: make deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: build/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y gcc make rpm-build sqlite-devel libcurl-devel systemd findutils

      - name: Build .rpm package
        run: make rpm

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: build/*.rpm

  create-release:
    runs-on: ubuntu-latest
    needs: [build-deb, build-rpm]
    permissions:
      contents: write
    steps:
      - name: Download .deb artifact
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: dist

      - name: Download .rpm artifact
        uses: actions/download-artifact@v4
        with:
          name: rpm-package
          path: dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
