name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .deb and .rpm packages
        run: make docker-packages

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-packages
          path: |
            build/uptime-logger-*.rpm
            !build/uptime-logger-debuginfo-*.rpm
            !build/uptime-logger-debugsource-*.rpm
            !build/uptime-logger-*.src.rpm
            build/uptime-logger_*.deb
            !build/uptime-logger-dbgsym_*.deb

  create-release:
    runs-on: ubuntu-latest
    needs: [build-packages]
    permissions:
      contents: write
    steps:
      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*